#!/bin/bash

# Quick guide to fix the localhost issue

echo "════════════════════════════════════════════════════════════════"
echo "🚨 URGENT FIX NEEDED - Your Vercel app is using LOCALHOST! 🚨"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "THE PROBLEM:"
echo "Your Vercel deployment is trying to connect to localhost:8000"
echo "instead of your production backend: https://arai-system.onrender.com"
echo ""
echo "════════════════════════════════════════════════════════════════"
echo "✅ FOLLOW THESE EXACT STEPS:"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "1️⃣  Open this URL in your browser:"
echo "   👉 https://vercel.com/dashboard"
echo ""
echo "2️⃣  Click on your project:"
echo "   👉 Look for 'arai-system' or similar name"
echo ""
echo "3️⃣  Click 'Settings' tab (top navigation)"
echo ""
echo "4️⃣  Click 'Environment Variables' (left sidebar)"
echo ""
echo "5️⃣  Click 'Add New' button"
echo ""
echo "6️⃣  Fill in these details:"
echo "   Name:  REACT_APP_API_URL"
echo "   Value: https://arai-system.onrender.com/api/v1"
echo ""
echo "7️⃣  Select ALL environments:"
echo "   ✅ Production"
echo "   ✅ Preview"
echo "   ✅ Development"
echo ""
echo "8️⃣  Click 'Save'"
echo ""
echo "════════════════════════════════════════════════════════════════"
echo "🔄 NOW REDEPLOY (CRITICAL - DON'T SKIP!):"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "9️⃣  Click 'Deployments' tab"
echo ""
echo "🔟 Find the latest deployment (top of the list)"
echo ""
echo "1️⃣1️⃣  Click the '⋯' (three dots) button on the right"
echo ""
echo "1️⃣2️⃣  Click 'Redeploy'"
echo ""
echo "1️⃣3️⃣  Click 'Redeploy' again to confirm"
echo ""
echo "1️⃣4️⃣  Wait 2-3 minutes for 'Building...' to change to 'Ready'"
echo ""
echo "════════════════════════════════════════════════════════════════"
echo "🧪 THEN TEST:"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "1. Open NEW Incognito/Private window"
echo "2. Go to: https://arai-system.vercel.app"
echo "3. Sign in"
echo "4. Press F12 (open DevTools)"
echo "5. Go to Console tab"
echo "6. Upload an image"
echo "7. Click 'Analyze Design'"
echo ""
echo "You should see a request to:"
echo "https://arai-system.onrender.com/api/v1/analysis/upload"
echo ""
echo "NOT localhost:8000!"
echo ""
echo "════════════════════════════════════════════════════════════════"
echo "⚠️  CRITICAL REMINDER:"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "Environment variables in Vercel are NOT read from your code!"
echo "They MUST be set manually in Vercel Dashboard!"
echo "You MUST redeploy after adding them!"
echo ""
echo "════════════════════════════════════════════════════════════════"

# Visual separator
echo ""
read -p "Press ENTER after you've completed all steps above..."
echo ""
echo "Great! Now wait 2-3 minutes and test your app."
echo ""
echo "If you still see 'localhost' in the console errors:"
echo "  1. Hard refresh: Cmd+Shift+R (Mac) or Ctrl+Shift+F5 (Windows)"
echo "  2. Use Incognito mode"
echo "  3. Check you redeployed in Vercel"
echo ""
echo "════════════════════════════════════════════════════════════════"
