#!/bin/bash

# 🔧 Fix CORS Issue - Run this script to update Railway CORS settings

echo "🔧 Updating Railway CORS Settings..."
echo ""
echo "Option 1: Via Railway Dashboard (RECOMMENDED)"
echo "=============================================="
echo "1. Go to: https://railway.com/project/2dee3236-8f3c-4a8c-a7d0-1843e49cf69f"
echo "2. Click on 'arai-system' service"
echo "3. Go to 'Variables' tab"
echo "4. Add or update: ALLOWED_ORIGINS"
echo "5. Set value to: https://frontend-seven-alpha-91.vercel.app"
echo "6. Click 'Add' or 'Update'"
echo "7. Railway will automatically redeploy (30-60 seconds)"
echo ""
echo "Option 2: Via Railway CLI"
echo "========================="
echo "Run this command:"
echo ""
echo "  railway variables set ALLOWED_ORIGINS='https://frontend-seven-alpha-91.vercel.app'"
echo ""
echo "✅ After updating, test your frontend at:"
echo "   https://frontend-seven-alpha-91.vercel.app"
echo ""
echo "🧪 To verify CORS is working, run:"
echo "   curl -X OPTIONS https://arai-system-production.up.railway.app/api/v1/auth/signup \\"
echo "     -H 'Origin: https://frontend-seven-alpha-91.vercel.app' \\"
echo "     -H 'Access-Control-Request-Method: POST' \\"
echo "     -v 2>&1 | grep -i 'access-control-allow-origin'"
echo ""
echo "Expected output:"
echo "   < access-control-allow-origin: https://frontend-seven-alpha-91.vercel.app"
